clc
clear
cls

%% GEO Formation Flying - HCW方程式による相対軌道運動の数値シミュレーション
const = orbitConst();

% GEO軌道パラメータ
mu = const.GE; % 地球重力定数 [km^3/s^2]
aGeo = 42164;     % GEO軌道半径 [km]
n = sqrt(mu / aGeo^3); % GEO軌道角速度 [rad/s] (約24時間周期)
T = 2*pi/n;    % 軌道周期 [s]

dMin = 0.5; % 最小相対距離 [km]
dMax = 1; % 最大相対距離 [km]

fprintf('GEO軌道パラメータ:\n')
fprintf('軌道角速度: %.6e rad/s\n', n)
fprintf('軌道周期: %.2f hours\n', T/3600)

% Formation Flying初期条件 [km, km/s]
% 典型的なGEO formation flyingの相対距離（数km）
xIni = 5;   % x方向初期位置 (radial) [km]
yIni = 10 ;      % y方向初期位置 (along-track) [km]
zIni = 10;   % z方向初期位置 (cross-track) [km]
vxIni = 0;     % x方向初期速度 [km/s]
vyIni = -2 * n * xIni; % y方向初期速度 (small along-track velocity) [km/s]
vzIni = 0;     % z方向初期速度 [km/s]

% 初期状態ベクトル
stateIni = [xIni; yIni; zIni; vxIni; vyIni; vzIni];

% シミュレーション時間（1軌道周期）
dt = 10;
timeSpan = 0:dt:1*T;
opts = odeset('RelTol', 1e-10, 'AbsTol', 1e-10);
% 数値積分（ode45を使用）
[timeSim, stateHistory] = ode45(@(t,x) eomHCW(t,x,n), timeSpan, stateIni, opts);

% 結果の抽出
x = stateHistory(:,1);
y = stateHistory(:,2);
z = stateHistory(:,3);
vx = stateHistory(:,4);
vy = stateHistory(:,5);
vz = stateHistory(:,6);

% modal variables
phi = atan2(vxIni, 3*n*xIni + 2*vyIni);
A0 = sqrt((3 * xIni + 2 * vyIni / n)^2 + (vxIni / n)^2)
xoff = 4 * xIni + 2 * vyIni / n;
min(x)
xoff - A0
(2*pi-phi) /n / T

%% 結果の可視化

% 3D軌道プロット
figure(1)
plot3(x, y, z, 'b-', 'LineWidth', 2)
hold on
plot3(xIni, yIni, zIni, 'go', 'MarkerSize', 8, 'MarkerFaceColor', 'g')
plot3(x(end), y(end), z(end), 'ro', 'MarkerSize', 8, 'MarkerFaceColor', 'r')
grid on
xlabel('x [km] (Radial)')
ylabel('y [km] (Along-track)')
zlabel('z [km] (Cross-track)')
title('HCW方程式による相対軌道運動')
legend('軌道', '初期位置', '最終位置', 'Location', 'best')
axis equal

% x-y平面での軌道
figure(2)
subplot(2,1,1)
plot(y, x, 'b-', 'LineWidth', 2)
hold on
plot(yIni, xIni, 'go', 'MarkerSize', 8, 'MarkerFaceColor', 'g')
plot(y(end), x(end), 'ro', 'MarkerSize', 8, 'MarkerFaceColor', 'r')
set(gca, 'XDir', 'reverse')
legend('軌道', '初期位置', '最終位置', 'Location', 'best')
grid on
xlabel('y [km] (Along-track)')
ylabel('x [km] (Radial)')
title('RT平面での軌道')
axis equal

% x-y平面での軌道 (zoom plot)
subplot(2,1,2)
plot(y, x, 'b-', 'LineWidth', 2)
set(gca, 'XDir', 'reverse')
xlim([-dMax, dMax])
ylim([-dMax, dMax])
grid on
xlabel('y [km] (Along-track)')
ylabel('x [km] (Radial)')
title('RT平面での軌道 (zoom plot, dMin = 0.5 km, dMax = 1 km)')


figure(4)
plot(timeSim/T, x, 'b-', 'LineWidth', 2)
hold on
grid on
xlabel('時間 [orbit]')
ylabel('x [km]')
title('x方向位置')

fprintf('シミュレーション完了\n')
fprintf('初期位置: [%.3f, %.3f, %.3f] km\n', xIni, yIni, zIni)
fprintf('最終位置: [%.3f, %.3f, %.3f] km\n', x(end), y(end), z(end))
fprintf('最大距離: %.3f km\n', max(sqrt(x.^2 + y.^2 + z.^2)))

%% rendering 用 CSV 出力
% mRendering の `mrender.py relative --mode csv --rel-csv ...` で読み込む形式。
% 列: time_s, x, y, z, qx, qy, qz, qw（スカラーラスト、姿勢は恒等で固定）
%
% 注意: HCW の (x, y, z) = (radial, along-track, cross-track) [km]。
% シーン単位は任意なので、必要に応じて relPos のスケールを調整すること。
relScale = 1.0;                       % km → シーン単位の倍率（1.0 = km をそのまま）
relPos = [x, y, z] * relScale;        % (N, 3)
nSamples = length(timeSim);
relQuat = repmat([0, 0, 0, 1], nSamples, 1);  % 姿勢恒等 [qx qy qz qw]

csvData = [timeSim, relPos, relQuat];

[scriptDir, ~, ~] = fileparts(mfilename('fullpath'));
projectRoot = fileparts(scriptDir);
inputDir = fullfile(projectRoot, 'input');
if ~exist(inputDir, 'dir')
    mkdir(inputDir);
end
csvPath = fullfile(inputDir, 'rel_state_hcw.csv');

fid = fopen(csvPath, 'w');
fprintf(fid, '# Generated by matlabSample/mainHCW.m\n');
fprintf(fid, '# HCW relative motion (radial, along-track, cross-track) [km], identity attitude\n');
fprintf(fid, 'time_s,x,y,z,qx,qy,qz,qw\n');
fclose(fid);
writematrix(csvData, csvPath, 'WriteMode', 'append');

fprintf('\nレンダリング用 CSV（相対）を出力: %s\n', csvPath);
fprintf('  サンプル数: %d、時間範囲: 0 〜 %.1f s\n', nSamples, timeSim(end));
fprintf('使用例（mrender.py relative）:\n');
fprintf('  python mrender.py relative --mode csv --rel-csv input/rel_state_hcw.csv \\\n');
fprintf('      --frames %d --fps %.2f\n', nSamples, 1/dt);

%% rendering 用 CSV 出力（絶対軌道）
% HCW の RTN 相対状態 (x, y, z, vx, vy, vz) を ECI 絶対状態 (r, v) に変換し、
% さらに yoshimuLibrary の rv2oe でケプラー軌道要素（osculating）へ変換して
% mRendering の `orbit_mechanics.CsvEphemeris` 互換形式で出力する。
%
% フォーマット: time_s, a_km, e, inc_rad, raan_rad, ome_rad, f_rad
% chief は GEO 円軌道（赤道面、t=0 で +x 方向）を仮定:
%   r_chief(t) = a * [cos(n t); sin(n t); 0]
%   v_chief(t) = a n * [-sin(n t); cos(n t); 0]
% LVLH (RTN) 基底（chief は円軌道なので解析的に書ける）:
%   x_h = r̂ = [cos(nt), sin(nt), 0]      (radial)
%   y_h = t̂ = [-sin(nt), cos(nt), 0]     (along-track, = v̂)
%   z_h = ĥ = [0, 0, 1]                   (orbit normal, cross-track)
% deputy_r_ECI = r_chief + R_lvlh2eci * [x; y; z]_RTN
% deputy_v_ECI = v_chief + ω × (R_lvlh2eci * ρ) + R_lvlh2eci * ρ̇   (ω = n * ẑ)

aChiefKm = aGeo;
th = n * timeSim;
cTh = cos(th);
sTh = sin(th);
zCol = zeros(nSamples, 1);

% Chief 絶対状態（解析的、N×3）
rChief = aChiefKm     * [cTh,  sTh,  zCol];
vChief = aChiefKm * n * [-sTh, cTh,  zCol];

% LVLH 基底（行ベクトル並び、N×3 各列）
rHat = [cTh,  sTh, zCol];
tHat = [-sTh, cTh, zCol];
wHat = repmat([0, 0, 1], nSamples, 1);

% deputy 相対状態を ECI へ展開: ρ = x rHat + y tHat + z wHat
rhoEci    = x  .* rHat + y  .* tHat + z  .* wHat;
rhoDotEci = vx .* rHat + vy .* tHat + vz .* wHat;

% LVLH 系の ECI に対する角速度（chief 円軌道なので一定）
omegaOrbit = repmat([0, 0, n], nSamples, 1);

% 転置定理: v_dep_eci = v_chief + ω × ρ_eci + ρ̇_eci
rDeputy = rChief + rhoEci;
vDeputy = vChief + cross(omegaOrbit, rhoEci, 2) + rhoDotEci;

% yoshimuLibrary の rv2oe（行ベクトル N×3 入力対応、出力 [a, e, inc, raan, w, nu]）。
% chief は円・赤道軌道なので rv2oe の特異点（e=0 でゼロ除算 → nu 複素数）に当たる。
% 解析的に書ける（a=aGeo, e=0, inc=0, raan=0, w=0, nu=n t = 真経度）ので直書きする。
oeChief = [aChiefKm * ones(nSamples, 1), ...
           zeros(nSamples, 1), ...
           zeros(nSamples, 1), ...
           zeros(nSamples, 1), ...
           zeros(nSamples, 1), ...
           mod(th, 2*pi)];

% deputy は HCW 解により楕円・微傾斜軌道になるので rv2oe を直接適用可能。
oeDeputy = rv2oe(rDeputy, vDeputy, mu);

chiefAbsPath  = fullfile(inputDir, 'abs_chief_hcw.csv');
deputyAbsPath = fullfile(inputDir, 'abs_deputy_hcw.csv');
writeOeCsv(chiefAbsPath,  timeSim, oeChief);
writeOeCsv(deputyAbsPath, timeSim, oeDeputy);

fprintf('\nレンダリング用 CSV（絶対軌道）を出力:\n');
fprintf('  chief  : %s\n', chiefAbsPath);
fprintf('  deputy : %s\n', deputyAbsPath);
fprintf('使用例（mrender.py render、YAML 内で objects: として参照）:\n');
fprintf('  objects:\n');
fprintf('    - name: chief\n      csv_path: input/abs_chief_hcw.csv\n');
fprintf('    - name: deputy\n      csv_path: input/abs_deputy_hcw.csv\n');


%% --- ローカル関数 ---
function writeOeCsv(path, timeVec, oe)
    fid = fopen(path, 'w');
    fprintf(fid, '# Generated by matlabSample/mainHCW.m\n');
    fprintf(fid, '# Osculating Keplerian elements (chief: GEO circular equatorial)\n');
    fprintf(fid, '# Columns match mRendering orbit_mechanics.CsvEphemeris.\n');
    fprintf(fid, 'time_s,a_km,e,inc_rad,raan_rad,ome_rad,f_rad\n');
    fclose(fid);
    writematrix([timeVec, oe], path, 'WriteMode', 'append');
end

